
name: hlf-network
version: 1.0.0
client:
  organization: ""
organizations:
  
  ordMSP:
    mspid: ordMSP
    cryptoPath: /tmp/cryptopath
    users: {}
    peers: []
    orderers:
      - ord-node0.default
      - ord-node1.default
      - ord-node2.default
      - ord-node3.default
  org1MSP:
    mspid: org1MSP
    cryptoPath: /tmp/cryptopath
    users:
      org1-admin-default:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUzCCAfmgAwIBAgIUHfHErpUq6bfvRUjX7eY+ZSf/P/EwCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjUxMTE1MTkwNTIxWhcNMjYxMTE2MTkwNjAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAARt+OWwLA2fpFOjTNqTqopKujHtedsWB5BaAaWYGcFc+UE/9ztnxfB2
            0o+x8OupW2+CCZR3Nhoc/jJXRV4wx9KSo4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSQuSYNhI7iPzXcytH/dU8v3demBzArBgNV
            HSMEJDAigCBaRAb8r0GTt5JIEYsSQ1i/4NHZuUQmXxQ6DUzWaGjvCjBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0gA
            MEUCIQCYQTvqU/z90Ilprx3BHGX3rU7F8BAvIb9d4jlVEMMKSAIgeIUU2C24lHjf
            7bZULW3+e7onBl+YLTKPqtnQd+5iwMo=
            -----END CERTIFICATE-----
            
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg8kWSWzfvS+/vOkSe
            ka9fv1i7MbV66mmF8A3Jf0TjFRuhRANCAARt+OWwLA2fpFOjTNqTqopKujHtedsW
            B5BaAaWYGcFc+UE/9ztnxfB20o+x8OupW2+CCZR3Nhoc/jJXRV4wx9KS
            -----END PRIVATE KEY-----
            
    peers:
      - org1-peer0.default
      - org1-peer1.default
    orderers: []

orderers:
  ord-node0.default:

    url: grpcs://node0-ord.localho.st:443


    adminUrl: https://admin-orderer0-ord.localho.st:443
    adminTlsCert: |
        -----BEGIN CERTIFICATE-----
        MIIC9DCCApqgAwIBAgIULGyiUmbUb0UA+mdEed47QLkl7fMwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjUxMTE1MTkwNjM3WhcNMjYxMTE2MTkwNzAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAEeKMIFoNjy1NcLqu/y2DGwTmvjqhBCS7ZVsJ7+R8Uic6v
        bcmELSj/Ec43DPy2X3GjSWj+iSTE5C0l9QCHdg71gaOCAV8wggFbMA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQU8kYs0+xbu1xlk8x8NY+t1SUb4z4wKwYDVR0jBCQwIoAg
        UXXD5URoNcYzI41ftxZ0Q6X3pMtG4jhvYJrLg5zI6DcwcwYDVR0RBGwwaoIJbG9j
        YWxob3N0gglvcmQtbm9kZTCCEW9yZC1ub2RlMC5kZWZhdWx0ghRub2RlMC1vcmQu
        bG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjAtb3JkLmxvY2FsaG8uc3SHBH8AAAGH
        BKwSAAIwWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIi
        LCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIi
        fX0wCgYIKoZIzj0EAwIDSAAwRQIhAOq0t8IVwOaFBT7u7k4oh5zYef5gTDZRMiLL
        UxaY6Gq2AiBpGccMGa1jWJB7T+fKq4g7QQE+M1McrpdwjVM/OctJew==
        -----END CERTIFICATE-----
        

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQPGz4AFf7RDBoW2eqERoVOTAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTUxOTA2MzdaFw0zNTExMTYxOTA2MzdaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+zp6Cw0KyI64vosu
        9S2WvB3tMcYJ+hbHRfgt3A6vxWl87PWmlHl5cTv2JCup5FnHAGTbUvjEZnkjreTH
        QfjQ1KNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBRdcPlRGg1xjMjjV+3
        FnRDpfeky0biOG9gmsuDnMjoNzAKBggqhkjOPQQDAgNJADBGAiEAlJcQsSHLV2kd
        qEvOcfM8vECD4XNQYSgG5V7PqHvfsukCIQCw3cIKex8M7/S9PyTURN94X+nMP06X
        ZzjoirfUEr5A2Q==
        -----END CERTIFICATE-----
        
  ord-node1.default:

    url: grpcs://node1-ord.localho.st:443


    adminUrl: https://admin-orderer1-ord.localho.st:443
    adminTlsCert: |
        -----BEGIN CERTIFICATE-----
        MIIC8zCCApqgAwIBAgIUQ+sNS/yrl5uQaGjxn0MsSqlrRVEwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjUxMTE1MTkwNjM3WhcNMjYxMTE2MTkwNzAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAE9nkyLtfLrSdZ+UtCE7nf5ztizHfmtbO6xTqm/Ex1QiPw
        ExVuz5eWTbyRkafQv9E/mzCELziOEkfZJA9DNB6T/qOCAV8wggFbMA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUdst3cttqy+Elo9yRK3qqsVMA/XAwKwYDVR0jBCQwIoAg
        UXXD5URoNcYzI41ftxZ0Q6X3pMtG4jhvYJrLg5zI6DcwcwYDVR0RBGwwaoIJbG9j
        YWxob3N0gglvcmQtbm9kZTGCEW9yZC1ub2RlMS5kZWZhdWx0ghRub2RlMS1vcmQu
        bG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjEtb3JkLmxvY2FsaG8uc3SHBH8AAAGH
        BKwSAAIwWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIi
        LCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIi
        fX0wCgYIKoZIzj0EAwIDRwAwRAIgLWgKeJIQpDkBsxppNzFMy3AF4/V3s5QeQf9m
        daSUjF0CIHvEi8XJwmrO4/2ADDZv4Q/+m7phFJkH6iqJO+Iq5yY8
        -----END CERTIFICATE-----
        

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQPGz4AFf7RDBoW2eqERoVOTAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTUxOTA2MzdaFw0zNTExMTYxOTA2MzdaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+zp6Cw0KyI64vosu
        9S2WvB3tMcYJ+hbHRfgt3A6vxWl87PWmlHl5cTv2JCup5FnHAGTbUvjEZnkjreTH
        QfjQ1KNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBRdcPlRGg1xjMjjV+3
        FnRDpfeky0biOG9gmsuDnMjoNzAKBggqhkjOPQQDAgNJADBGAiEAlJcQsSHLV2kd
        qEvOcfM8vECD4XNQYSgG5V7PqHvfsukCIQCw3cIKex8M7/S9PyTURN94X+nMP06X
        ZzjoirfUEr5A2Q==
        -----END CERTIFICATE-----
        
  ord-node2.default:

    url: grpcs://node2-ord.localho.st:443


    adminUrl: https://admin-orderer2-ord.localho.st:443
    adminTlsCert: |
        -----BEGIN CERTIFICATE-----
        MIIC9DCCApqgAwIBAgIUSYMyTBHhIl2fRuJfiqYHYMK/L6wwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjUxMTE1MTkwNjM3WhcNMjYxMTE2MTkwNzAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAERG0kUlFQLZKzbzxVNAMufdD8Y6vX9Rmo5vymeQhvlj0k
        zdPPFPqQjSeFT6hu+1iIInOGcFl9NtvFaBXj1QJwq6OCAV8wggFbMA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQU/rNTYPapz+LEV+5qQcipExL9vx0wKwYDVR0jBCQwIoAg
        UXXD5URoNcYzI41ftxZ0Q6X3pMtG4jhvYJrLg5zI6DcwcwYDVR0RBGwwaoIJbG9j
        YWxob3N0gglvcmQtbm9kZTKCEW9yZC1ub2RlMi5kZWZhdWx0ghRub2RlMi1vcmQu
        bG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjItb3JkLmxvY2FsaG8uc3SHBH8AAAGH
        BKwSAAIwWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIi
        LCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIi
        fX0wCgYIKoZIzj0EAwIDSAAwRQIhAMVSKG5HFkXzVq00/KoJMiMggXbe9y85dSJE
        lX/c2e6lAiBfHb2nzAvK0ejMVQ6b8PBkNdsw/u2oXfCIV5S/LECkWA==
        -----END CERTIFICATE-----
        

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQPGz4AFf7RDBoW2eqERoVOTAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTUxOTA2MzdaFw0zNTExMTYxOTA2MzdaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+zp6Cw0KyI64vosu
        9S2WvB3tMcYJ+hbHRfgt3A6vxWl87PWmlHl5cTv2JCup5FnHAGTbUvjEZnkjreTH
        QfjQ1KNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBRdcPlRGg1xjMjjV+3
        FnRDpfeky0biOG9gmsuDnMjoNzAKBggqhkjOPQQDAgNJADBGAiEAlJcQsSHLV2kd
        qEvOcfM8vECD4XNQYSgG5V7PqHvfsukCIQCw3cIKex8M7/S9PyTURN94X+nMP06X
        ZzjoirfUEr5A2Q==
        -----END CERTIFICATE-----
        
  ord-node3.default:

    url: grpcs://node3-ord.localho.st:443


    adminUrl: https://admin-orderer3-ord.localho.st:443
    adminTlsCert: |
        -----BEGIN CERTIFICATE-----
        MIIC9DCCApqgAwIBAgIUGRKbTztUeDBoX49yExduKRtmjPowCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjUxMTE1MTkwNjM3WhcNMjYxMTE2MTkwODAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAEBVqdsufFMHNoWF3IT9l9LpVCaM1eBj4x5jtQw2JlPKif
        BzRjW3bjxYPNDRliZbx+XWNcu6WZz69gfF+n29xsyaOCAV8wggFbMA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUOaiThfGcHqbrNDPERHs3zTuLEMswKwYDVR0jBCQwIoAg
        UXXD5URoNcYzI41ftxZ0Q6X3pMtG4jhvYJrLg5zI6DcwcwYDVR0RBGwwaoIJbG9j
        YWxob3N0gglvcmQtbm9kZTOCEW9yZC1ub2RlMy5kZWZhdWx0ghRub2RlMy1vcmQu
        bG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjMtb3JkLmxvY2FsaG8uc3SHBH8AAAGH
        BKwSAAIwWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIi
        LCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIi
        fX0wCgYIKoZIzj0EAwIDSAAwRQIhAMNOi3Q/+fsPmxo2Cr+3OM5X+8Q6LzFwzthz
        AkkfkFL4AiAVcO8reOx0GADqV7nu7dqNN3JAbeu2MgZ1FsKvGt50TA==
        -----END CERTIFICATE-----
        

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQPGz4AFf7RDBoW2eqERoVOTAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTUxOTA2MzdaFw0zNTExMTYxOTA2MzdaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+zp6Cw0KyI64vosu
        9S2WvB3tMcYJ+hbHRfgt3A6vxWl87PWmlHl5cTv2JCup5FnHAGTbUvjEZnkjreTH
        QfjQ1KNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBRdcPlRGg1xjMjjV+3
        FnRDpfeky0biOG9gmsuDnMjoNzAKBggqhkjOPQQDAgNJADBGAiEAlJcQsSHLV2kd
        qEvOcfM8vECD4XNQYSgG5V7PqHvfsukCIQCw3cIKex8M7/S9PyTURN94X+nMP06X
        ZzjoirfUEr5A2Q==
        -----END CERTIFICATE-----
        


peers:
  org1-peer0.default:

    url: grpcs://peer0-org1.localho.st:443

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQLFaL9Zh88UrmF6V1aAtIxjAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTUxOTA1MjFaFw0zNTExMTYxOTA1MjFaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9v/ovhB08QlPQ0UP
        lrfS+Lha5TUrHGdS7oUpt85Ef74JT/7+tHZ4G5KvCJU+sHLPU8De92xtpefAXet0
        6/gctKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCpSW+AWPWPEvWG41sR
        /jswccNsgaKGcMZ0a5kmB4vp8TAKBggqhkjOPQQDAgNJADBGAiEA+0im7P2bLyHg
        ByukydSZFLevQpRWExbfgYEWCYN6AsUCIQDTXNuy3rLUL9ym2UB9K5ddEFrSdD0A
        TO57RejyYszKbA==
        -----END CERTIFICATE-----
        
  org1-peer1.default:

    url: grpcs://peer1-org1.localho.st:443

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQLFaL9Zh88UrmF6V1aAtIxjAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTUxOTA1MjFaFw0zNTExMTYxOTA1MjFaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9v/ovhB08QlPQ0UP
        lrfS+Lha5TUrHGdS7oUpt85Ef74JT/7+tHZ4G5KvCJU+sHLPU8De92xtpefAXet0
        6/gctKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCpSW+AWPWPEvWG41sR
        /jswccNsgaKGcMZ0a5kmB4vp8TAKBggqhkjOPQQDAgNJADBGAiEA+0im7P2bLyHg
        ByukydSZFLevQpRWExbfgYEWCYN6AsUCIQDTXNuy3rLUL9ym2UB9K5ddEFrSdD0A
        TO57RejyYszKbA==
        -----END CERTIFICATE-----
        
certificateAuthorities:
  
  ord-ca.default:

    url: https://ord-ca.localho.st:443


    registrar:
        enrollId: enroll
        enrollSecret: "enrollpw"

    caName: ca
    tlsCACerts:
      pem: 
       - |
            -----BEGIN CERTIFICATE-----
            MIICWTCCAf+gAwIBAgIRAOHRQ2cIKCv1i2UZkwF7eGcwCgYIKoZIzj0EAwIwUjET
            MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
            BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjUxMTE1MTkwNjM3
            WhcNMzUxMTE2MTkwNjM3WjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
            EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
            YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABK8/cMsPZGzFvEipNiUc/EvM
            y7Mk44M3dHAdV2sv5uhnJXhnUmo90aVffqrvBXzM0SQz3gNzwM4KKQg7CDT/K8mj
            gbUwgbIwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
            BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBbzzNPiqb9xRTBPF/8aKhF
            Wr0Dd2WFJ4DqhRyCzdiv7zBFBgNVHREEPjA8gglsb2NhbGhvc3SCBm9yZC1jYYIO
            b3JkLWNhLmRlZmF1bHSCEW9yZC1jYS5sb2NhbGhvLnN0hwR/AAABMAoGCCqGSM49
            BAMCA0gAMEUCIFRItv8VvN9EeM11sSEL/U8w3KpujIPadD/mWvRzc1xpAiEA1JhO
            tSS4s8ZViZ0EVF724cs6bqNhNAjp0A+RFs1y1MM=
            -----END CERTIFICATE-----
            
  
  org1-ca.default:

    url: https://org1-ca.localho.st:443


    registrar:
        enrollId: enroll
        enrollSecret: "enrollpw"

    caName: ca
    tlsCACerts:
      pem: 
       - |
            -----BEGIN CERTIFICATE-----
            MIICWzCCAgGgAwIBAgIQHLLe6o3gmXSh328PQmphBTAKBggqhkjOPQQDAjBSMRMw
            EQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQHEwAxCTAHBgNVBAkTADEUMBIGA1UE
            ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzAeFw0yNTExMTUxOTA1MjFa
            Fw0zNTExMTYxOTA1MjFaMFIxEzARBgNVBAYTCkNhbGlmb3JuaWExCTAHBgNVBAcT
            ADEJMAcGA1UECRMAMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFi
            cmljMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEt/SxbwOxFeAwHuBS9TBXOP1K
            LhnLtroujpLuL3ja0CAqOJFUrESRcxPdxbM7B75Cs5WZTDiEaXNNJGor5rR8taOB
            uDCBtTAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUF
            BwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIHalzJqHigJogtsRfnCMIdmE
            2a7phsBsL3+dUPhM5vIxMEgGA1UdEQRBMD+CCWxvY2FsaG9zdIIHb3JnMS1jYYIP
            b3JnMS1jYS5kZWZhdWx0ghJvcmcxLWNhLmxvY2FsaG8uc3SHBH8AAAEwCgYIKoZI
            zj0EAwIDSAAwRQIgK/sP3G2yfeY92aHv9d92nXun+fC6aXBRLw9uL3IoJoMCIQDH
            OsKYlL4fSgLuMIpI8SEHvTxgpASrzFakBzFkTmeDMg==
            -----END CERTIFICATE-----
            


channels:
  demo:

    orderers:
      - ord-node0.default
      - ord-node1.default
      - ord-node2.default
      - ord-node3.default

    peers:
       org1-peer0.default:
        discover: true
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
       org1-peer1.default:
        discover: true
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

